#!/bin/sh

if [ "$1" == "config" ]; then
cat <<_FOO_
graph_title Facebook activity
graph_category social
graph_args --lower-limit 0.01 --logarithmic --units=si
fbstream.label Stream activity
fbstream.type GAUGE
fbfriends.label Friend count
fbfriends.type GAUGE
fbfonline.label Friends online
fbfonline.type GAUGE
messages_unread.label Unread messages
messages_unread.type GAUGE
pokes.label Pokes
pokes.type GAUGE
shares_unread.label Unread shares
shares_unread.type GAUGE
friend_requests.label Friend requests
friend_requests.type GAUGE
group_invites.label Group invites
group_invites.type GAUGE
event_invites.label Event invites
event_invites.type GAUGE
_FOO_
exit 0;
fi

echo -n 'fbstream.value '
fbcmd stream 0 new | grep "^\[" | wc -l | sed 's/\t +//' | sed 's/ *//'
echo -n 'fbfriends.value '
fbcmd friends | wc -l | sed 's/\t +//' | sed 's/ *//'
echo -n 'fbfonline.value '
fbcmd fonline | wc -l | sed 's/\t +//' | sed 's/ *//'

fbcmd notify | egrep "UNREAD|POKES|REQUESTS|INVITES" | sed 's/\t +//' | sed 's/ *//' | sed -e 's/ \+/.value /g' | tr '[:upper:]' '[:lower:]'

